# Generated by Django 3.1 on 2020-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва сторінки')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='Беграундна картинка')),
                ('slide_img_one', models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='1 Картинка в слайдері')),
                ('slide_img_two', models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='2 Картинка в слайдері')),
                ('slide_img_three', models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='3 Картинка в слайдері')),
                ('title_text', models.CharField(max_length=200, verbose_name='Заголовок тексту')),
                ('main_text', models.TextField(verbose_name='Опис сторінки')),
            ],
        ),
    ]
