# Generated by Django 3.1 on 2020-08-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Введіть назву категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Сторінка', 'verbose_name_plural': 'Сторінки'},
        ),
        migrations.AddField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(help_text='Виберіть категорію сторінки', to='main.TypePage'),
        ),
    ]
