# Generated by Django 3.1 on 2020-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200812_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url_page',
            field=models.SlugField(default=0, max_length=130, unique=True, verbose_name='Юрл сторінки'),
        ),
    ]
