# Generated by Django 3.1 on 2020-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200819_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='categories',
        ),
        migrations.AddField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(help_text='Виберіть категорію сторінки', to='main.TypePage'),
        ),
    ]
