# Generated by Django 3.1 on 2020-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200819_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slide_on_index',
            field=models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='Картинка на головній сторінці'),
        ),
    ]
