# Generated by Django 3.1 on 2020-11-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_page_slide_on_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slide_on_index',
        ),
        migrations.CreateModel(
            name='Fav_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_on_index', models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='Картинка на головній сторінці')),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
        ),
    ]
