# Generated by Django 3.1 on 2020-11-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201118_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fav_cat',
            new_name='Fav_page',
        ),
        migrations.AlterModelOptions(
            name='fav_page',
            options={'verbose_name': 'Сторінка на головній', 'verbose_name_plural': 'Сторінки на головній'},
        ),
    ]
