# Generated by Django 3.1 on 2020-11-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201118_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slide_on_index',
            field=models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='Картинка на головній сторінці'),
        ),
    ]
